### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by vincentarelbundock** [grantmcdermott/tinyplot#110]
I think it would be nice to have a simple logo for `plot2`.

I'm not a designer, and I'm unlikely to have other ideas, but here's a simple one (with help of GPT and some manual edits). It's probably not objectively great, but I like that it's simple and that the 2 could be used as favicon.

![plot2](https://github.com/grantmcdermott/plot2/assets/987057/52d03af0-e354-4e79-9460-ff53a1111980)

**Comment by grantmcdermott** [comment]
Thanks, yeah it's a good idea. A logo would be cool and it's nice to have ChatGPT's help here.. (Alternatively, Maybe something produced by the package itself, [like I did](https://grantmcdermott.com/parttree/articles/parttree-art.html#example-2-parttree-logo) for `parttree`?

Let's finalise the package name then take it up from there.

**Comment by grantmcdermott** [comment]
I was thinking of a stylised easel containing a plot. Here's the first thing DALL-E gives me, which is actually pretty cool. Could probably edit out a few of those extra points, but I like the vibe.

![file-15Gi3Zfh5QI4h4SSrhQ3W51T (2)](https://github.com/grantmcdermott/tinyplot/assets/10285037/e695431a-7954-4856-aac7-cfb9acf9ded8)

**Comment by vincentarelbundock** [comment]
I like it!

I've tried asking it to make plots simpler but it always seems to struggle. Once I asked it for 20 versions of the same logo and picked one, converted it to svg in inkscape, and got something reasonable.

**Comment by vincentarelbundock** [comment]
![easel](https://github.com/grantmcdermott/tinyplot/assets/987057/3b39dd19-6be5-4383-97c8-63059b630d86)

**Comment by zeileis** [comment]
Some comments and impressions, just my two cents. Feel free to disagree or ignore!
- Both icons are "ok" in my opinion but I think they are not the most memorable.
- I like the minimalistic style of the latter but would prefer something with more color...given that it is a graphics package.
- The main aspect I don't like is that an easel is not "tiny". But I couldn't think of an easily recognizable device that is tiny. A clipboard is probably still too large.

When thinking about the name, I had the following association which I quickly drew in very poor quality in GIMP. Again feel free to dislike or ignore.

![tinyplot drawing](https://github.com/grantmcdermott/tinyplot/assets/61125774/c19aeb9c-0956-4117-aa8e-2a9d26c92800)

**Comment by grantmcdermott** [comment]
+1 to whimsy and a pop of colour.

One thing I _do_ like about the original DALL-E drawing that I got was that it looks "cute", which is kind of synonymous with "tiny" in my mind. I'm going to share these with my wife (who actually works in the architecture/design industry and is thus much more qualified than me) for some opinions :-)

**Comment by zeileis** [comment]
Asking the wife is always a good idea!

On Monday my very talented colleague Reto will be back in the office. I'll also ask him for his opinion and possibly an alternative idea. He has helped me with quite a few logos and icons in the past:

<img src="https://colorspace.r-forge.r-project.org/logo.png" height=200/> <img src="https://topmodels.R-Forge.R-project.org/reference/figures/logo_hex.png" height=200/> <img src="https://www.mathe4wiwi.org/icon-video.png" height=200/>

**Comment by grantmcdermott** [comment]
Hi both, I plan to submit to CRAN this even (finally!).

But I wanted to circle back to this issue first. I've re-jigged my easel idea a bit. See attached. I think it makes for a decent enough logo, so I'm going to run with it. We can always revisit and potentially redo down the line.

![logo](https://github.com/grantmcdermott/tinyplot/assets/10285037/8df95bb5-24c5-47ba-9e82-5614dc080ac4)

(Achim, I'm not sure if anything came of your conversations with Reto, but please feel fee to share any ideas/logos that he proposed.)

**Comment by vincentarelbundock** [comment]
Looks great!

**Comment by zeileis** [comment]
I like it. It has a bit of a "great wave" vibe.

(Re: Reto. He had so many other things on his plate that I didn't want to add to that so I haven't asked, yet.)
