### ISSUE TITLE
Reduce size of installed package

### ISSUE THREAD

**Issue by grantmcdermott** [grantmcdermott/tinyplot#111]
This is > 5 MB, primarily due to all of the test snapshots in `inst/tinytest`.

As per R CMD check:

```
❯ checking installed package size ... NOTE
    installed size is  7.5Mb
    sub-directories of 1Mb or more:
      doc        3.0Mb
      help       1.5Mb
      tinytest   2.9Mb
```

Can we retain the GitHub testing infrastructure but skip it on CRAN? This is something that I don't have experience with, but I imagine there's a simple workaround.

**Comment by grantmcdermott** [comment]
@vincentarelbundock writes ([original comment](https://github.com/grantmcdermott/plot2/issues/108#issuecomment-1913120392))

> To skip on CRAN, I set an environment variable on the GitHub workflow and on my computer. Then, at the top of the test script I check if the flag is set with Sys.getenv and call tinytest::exit_file() if not.

That's a cool idea. But we would still need to manually add `inst/tinytest/_tinysnapshot` to `.Rbuildignore` before submission, right?

**Comment by vincentarelbundock** [comment]
Yep, or you could skip all the tests

**Comment by mdsumner** [comment]
I do a palettize of all image files *after* generation by the package, it's a bit crufty but it worked (using magick):

https://github.com/hypertidy/ceramic/blob/052b5f3e7608efa472d2ab0f84112f7ea4d5f625/README.Rmd#L230

**Comment by grantmcdermott** [comment]
> I do a palettize of all image files after generation by the package, it's a bit crufty but it worked (using magick)

That's interesting, thanks @mdsumner. I'm not sure whether it will work with the `tinysnapshot` testing workflow but I'll investigate when I get back to this.

**Comment by grantmcdermott** [comment]
@vincentarelbundock Do you mind taking a crack at this if you already have some boilerplate ENV VAR logic lying around?

(I'm still not quit sure how skipping the tests will get us around the snapshots if they're already bundled in `inst` . Probably just missing something obvious.)

**Comment by vincentarelbundock** [comment]
The process is kind of annoying, but this is what I do:

* Add this to my local `.zshrc` or equivalent: `export R_NOT_CRAN=true`
* Add a similar thing to Github workflow
* In `tests/tinytest.R`, add some logic to skip tests based on the environment variable using `Sys.getenv()`
* Before releasing to CRAN, add `inst/tinytest/_tinysnapshot` to `.Rbuildignore`

The last step is manual and should not be forgotten, which is not ideal.

**Comment by vincentarelbundock** [comment]
If you're fine with this workflow, I'll prep a PR

**Comment by grantmcdermott** [comment]
An additional thing that might consider doing here is not building the vignette(s).

**Comment by vincentarelbundock** [comment]
Honestly, I think I've come to the conclusion that package vignettes are not a good vehicle for tutorials when there are lots of visual elements and complex content. My simple packages have vignettes but those with more scope have a website.

**Comment by grantmcdermott** [comment]
You just add them to .Rbuildignore right? Do you have to make any adjustments to your altdoc CI workflow to get the website rendering to work properly?

**Comment by vincentarelbundock** [comment]
Yes, right. No, altdoc does not consider .Rbuildignore so everything in `vignettes/` gets built.

**Comment by grantmcdermott** [comment]
Great, let's do that then. I'll add this, then take a proper look at #128 too once I get time. (Slammed with work deadlines before I head out for an extended spring break...)

**Comment by eddelbuettel** [comment]
What @vincentarelbundock sketches above works, but there are other possible (related) ways.  

We could for example tie it up from the other end and start with the dreaded 'manual' tweak to `.Rbuildignore` and have that driven by a script (calling an R helper function you could call from R too) which
- temporarily adds the skip instruction to `.Rbuildignore`
- builds the release tarball
- removes the temporary instruction

If we take that as a given it becomes easier / cleaner to condition the tests. You can now check via `dir.exists()` if snapshot filess are present, and if not skip (even explicitly via `tinytest::exit_file("message here")` which I do a lot).  

You could also hook the call to the temporary modification into `cleanup`.  

There are other ways.  For example GitHub has a [boatload of environment vars](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables) including the standard `CI` (as most/all CI systems have) but also `GITHUB_ACTIONS` so you could use that to (at GitHub only) not skip etc.

Anyway, feel free to ignore, just trying to help if I can to shepherd this to CRAN.   (Also: 5mb is AFAIK not a  _hard_ constraint but I also haven't submitted a new 'yuge' package in a while...)
