### ISSUE TITLE
`tpar()` could pass extra arguments to `par()`

### ISSUE THREAD

**Issue by vincentarelbundock** [grantmcdermott/tinyplot#123]
Would be nice to have a single interface to set graphical parameters.

**Comment by grantmcdermott** [comment]
Question: Should we support setting/passing a default color `palette` through `tpar` too?

For example: `tpar(palette = "tableau")` or `tpar(palette = "harmonic")`?

Or is that trying to be too clever?

**Comment by zeileis** [comment]
I just noticed that I wanted to respond to this but never had:

I think adding `tpar(palette = ...)` would be consistent with having the added `tinyplot(..., palette = ...)` argument.

It could be useful when generating a sequence of similar plots and you want to use the same palette for all of them.

It's less useful for creating "themes" or so. For that it would be necessary to have a distinction between the default qualitative/categorical and the default sequential/ordered and the default diverging palette.

Hence, in summary, I think it would be of limited use - but it might be helpful for some and it would be easy to understand.
