### ISSUE TITLE
Support alpha = <numeric> and/or bg = <numeric> as shortcut for adjustcolor(col, <numeric>)?

### ISSUE THREAD

**Issue by zeileis** [grantmcdermott/tinyplot#129]
Should we support setting `bg = <numeric>` in [0, 1] as a shortcut for `bg = adjustcolor(col, <numeric>)` (as discussed in https://github.com/grantmcdermott/tinyplot/pull/122)?

This would be handy when we want to use `pch = 21:25` with some border `col` and then automatically use a semi-transparent version of the same color as the `bg` fill. But maybe this is too specialized and esoteric to implement a special shortcut.

Application example:

    p <- hcl.colors(120, rev = TRUE)[11:110]
    tinyplot(lat ~ long | depth, data = quakes, pch = 21, cex = 3, lwd = 2, col = p, bg = adjustcolor(p, 0.1))

The idea would be to abbreviate the last argument to just `bg = 0.1`.

![tinyplot with bg being a semi-transparent version of the main col](https://github.com/grantmcdermott/tinyplot/assets/61125774/8d0a5e14-dd6a-49b1-a8df-9b632dd88916)

**Comment by grantmcdermott** [comment]
Related to this, I wonder if we should support an `alpha = <[0,1]>`  argument for easy transparency of colours?

On a recent project, I find myself doing variants of  `plt(many_points, col = adjustcolor("black", 0.1)`. It would be nicer to just write `plt(many_points, alpha = 0.1)`. I'm not sure if this could be easily integrated with your `fill = [0,1]` idea, or whether they should exist as separate arguments. Probably the latter.

**Comment by zeileis** [comment]
I think that this will be nifty for some - and not confusing for those who don't need it. So it sounds like a useful addition to me.

... and I agree that it should be a separate argument.

**Comment by grantmcdermott** [comment]
FWIW, this now works in the [`cran`](https://github.com/grantmcdermott/tinyplot/tree/cran) branch.

``` r
library(tinyplot)

tinyplot(lat ~ long | depth, data = quakes, cex = 3, pch = 21, bg = 0.2)
```

![](https://i.imgur.com/gqdqoUd.png)

Similarly, for the `alpha` argument (which affects both the main col and fill, if applicable):

``` r
tinyplot(lat ~ long | depth, data = quakes, cex = 3, pch = 19, alpha = 0.2)
```

![](https://i.imgur.com/UHbaukn.png)


<sup>Created on 2024-06-17 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
