### ISSUE TITLE
Setting legend = "none" produces an error

### ISSUE THREAD

**Issue by datarichard** [grantmcdermott/tinyplot#131]
Setting the legend argument to "none" results in an error:  

`with(airquality, tinyplot(Day, Temp, by = Month, legend = "none"))`  

> Error in if (legend.args[["x"]] == "none" && isFALSE(add)) { : 
>  missing value where TRUE/FALSE needed  

(Setting the legend argument to `FALSE` works as expected)

(PPS: [Package tinyplot version 0.0.5.9000 [Index](http://127.0.0.1:57099/help/library/tinyplot/html/00Index.html)])

**Comment by grantmcdermott** [comment]
Thanks for the catch. Should be fixed now, but please let me know if not. 

(I think I introduced it whilst working towards the latest release, so I won't add a NEWS item.)
