### ISSUE TITLE
Switch README etc from iris to penguins?

### ISSUE THREAD

**Issue by eddelbuettel** [grantmcdermott/tinyplot#136]
The four examples in the README work quite well with one added `pp <- palmerpenguins::penguins`.  Here for example is the fourth as I just put it together for a slide:

![image](https://github.com/grantmcdermott/tinyplot/assets/673121/ff60ab81-2f13-4af2-9b7d-ec2605fe52a0)

**Comment by grantmcdermott** [comment]
Thanks @eddelbuettel. I thought about it a while back, but would prefer to stick with datasets in the `base` package for the quickstart example. Maybe once/if https://github.com/r-devel/r-svn/pull/154 is merged....

Plot looks good, though! One minor suggestion would be call `par(las = 1, lab = c(10,10,7))` beforehand to get better coverage across the axes. I hope to roll this kind of aesthetic automation into a `tinytheme()` function---[no relation](https://cloud.r-project.org/web/packages/tinythemes/index.html)---at some point.
