### ISSUE TITLE
How can we set per-plot color here?

### ISSUE THREAD

**Issue by eddelbuettel** [grantmcdermott/tinyplot#142]
The `datasauRus` package has a simple `ggplot2` example.  We can _almost_ do the same here with a one-liner:

```r
> tinyplot::plt(x ~ y, data=datasauRus::datasaurus_dozen, facet = ~ dataset, pch = 18)
> 
```

yielding a not-so-shabby

![image](https://github.com/grantmcdermott/tinyplot/assets/673121/ecaa5540-3488-4bf2-867f-720c13f2b0db)

But how can we jazz it up with, say, per panel plot colors? 

_Asking for a "friend" sitting here updating lecture slides on base plotting with a little `tinyplot` as one does ..._

**Comment by eddelbuettel** [comment]
Ah, nothing that one more minute of chin-scratching cannot solve:

```r
> tinyplot::plt(x ~ y | as.factor(dataset), data=datasauRus::datasaurus_dozen, facet = ~ dataset, pch = 18)
> 
```

![image](https://github.com/grantmcdermott/tinyplot/assets/673121/ebda997c-ee27-4194-a7fc-58d667e231f3)

Feel free to include this as a demo, credit appreciated.

**Comment by eddelbuettel** [comment]
Or prettier and more compact:

```r
> dd <- datasauRus::datasaurus_dozen
> tinyplot::plt(y ~ x | as.factor(dataset), data = dd, facet = ~ dataset, pch = 18, legend = FALSE)
> 
```

**Comment by grantmcdermott** [comment]
On vacation overlooking the beach but this should work for even more compact(er) and with less whitespace.

```r
tinyplot::plt(y ~ x | dataset, dd, facet = "by", pch = 18, legend = FALSE, frame = FALSE)
```

**Comment by eddelbuettel** [comment]
It's more or less the same (and I by now added a title).  On the marging I find `facet = ~ dataset` clearer.  The frame drop is so-so as we don't have a square layout:

![image](https://github.com/grantmcdermott/tinyplot/assets/673121/ef719ec3-4480-408e-8989-f9693086ebc8)
