### ISSUE TITLE
`"jitter"` (alias `"j"`?)

### ISSUE THREAD

**Issue by grantmcdermott** [grantmcdermott/tinyplot#169]

**Comment by vincentarelbundock** [comment]
This seems like points with something applied to them. Would also require some arguments. Maybe a candidate for "function factory" as suggested here: https://github.com/grantmcdermott/tinyplot/pull/168

**Comment by grantmcdermott** [comment]
> This seems like points with something applied to them. 

Yeah, I have a very simple implementation in mind that I'm about push through. Basically the same as `jitter(y) ~ jitter(x)`. We might consider adding a separate `jitter = TRUE` (or function) argument that could be applied to (some?) non point types.
