### ISSUE TITLE
CRAN 0.2.0 submission

### ISSUE THREAD

**Issue by grantmcdermott** [grantmcdermott/tinyplot#177]
I just realized that the CRAN team is taking its annual break very soon. I might try to submit a v0.2.0 of the package quickly, seeing as we've managed to accumulate a few nice [updates](https://github.com/grantmcdermott/tinyplot/blob/main/NEWS.md#01099-dev-version). Any objections @vincentarelbundock @zeileis?

**Comment by zeileis** [comment]
Good idea!

**Comment by grantmcdermott** [comment]
v0.2.0 is up on CRAN 🎉
