### ISSUE TITLE
Website isn't updating

### ISSUE THREAD

**Issue by grantmcdermott** [grantmcdermott/tinyplot#181]
E.g. See the rendered [NEWS](https://grantmcdermott.com/tinyplot/NEWS.html) versus the underlying GitHub [file](https://github.com/grantmcdermott/tinyplot/blob/main/NEWS.md).

Similarly for some changes to the intro vignette that I pushed a little earlier.

I saw that **altdoc** recently pushed a new [0.4.0](https://github.com/etiennebacher/altdoc/releases/tag/v0.4.0) release with some logic updates. Do we need to update our CI workflow?

cc @etiennebacher @vincentarelbundock

**Comment by etiennebacher** [comment]
FYI I can't look at this before middle of next week

**Comment by grantmcdermott** [comment]
Seems to be fixed by #185.
