### ISSUE TITLE
Boxplots widths too narrow if x == by

### ISSUE THREAD

**Issue by grantmcdermott** [grantmcdermott/tinyplot#195]
``` r
library(tinyplot)

tinyplot(
  Petal.Length ~ Species, iris,
  type = "boxplot"
)
```

![](https://i.imgur.com/5aEVlJJ.png)

``` r
tinyplot(
  Petal.Length ~ Species | Species, iris,
  type = "boxplot",
  legend = list("topleft", bty = "o")
)
```

![](https://i.imgur.com/1kFZDNQ.png)

The bottom boxplots should be the same width as the top ones. But they're too narrow.

I think I know why this is happening (related to a factor coercion) and should hopefully be a simple fix.

**Comment by grantmcdermott** [comment]
Oops, turning off the legend triggers a resizing error of its own.

``` r
tinyplot(
  Petal.Length ~ Species | Species, iris,
  type = "boxplot",
  legend = FALSE
)
```

![](https://i.imgur.com/5Zv8N0e.png)

This is a separate bug, but I'll try to address at the same time.

**Comment by zeileis** [comment]
Note also that you try to detect `x == by` only based on their levels which is not general enough. As a simple example, consider a coordination game of two players, where you want to know whether the `outcome` of the experiment depends on the combination of the gender of `player1` and `player2`. To visualize the boxplots of the four groups you can use `outcome ~ player1 | player2`. Thus `x != by` but `levels(x) == levels(by)`.

When `legend = FALSE` this case is handled correctly but by default it is not:

```
d <- data.frame(
  outcome = sin(1:40 - 3),
  player1 = factor(rep(c("female", "male"), each = 20)),
  player2 = factor(rep(rep(c("female", "male"), each = 10), 2))
)
tinyplot(outcome ~ player1 | player2, data = d)
tinyplot(outcome ~ player1 | player2, data = d, legend = FALSE)
```

<img src="https://github.com/user-attachments/assets/5939c997-cfce-4ac7-bb97-cdaf8420266b" width="49%" alt="default boxplot" />
<img src="https://github.com/user-attachments/assets/ae629d04-a515-45de-9cf8-2a611f3ae5ae" width="49%" alt="boxplot without legend" />

**Comment by grantmcdermott** [comment]
Good catch.

Hmmm. I'll probably have to move this logic higher up in the code and do something like `x_by = identical(x, by)`.

**Comment by zeileis** [comment]
Oh, and playing around with this some more: We currently cannot set any of the `boxplot.default` arguments, can we? For example, `range`, `varwidth`, `width`, `notch`, etc. seem to be ignored at the moment.

```
iris2 <- iris[c(1:30, 61:100, 101:150), ]
plot(Petal.Length ~ Species, data = iris2, varwidth = TRUE, range = 0.5, notch = TRUE)
tinyplot(Petal.Length ~ Species, data = iris2, varwidth = TRUE, range = 0.5, notch = TRUE)
```

![boxplots with varwidth/range/notch: base vs tinyplot](https://github.com/user-attachments/assets/7b493de5-c467-4a97-9adf-b714a8c09dc7)

But maybe this should be a separate issue?

**Comment by grantmcdermott** [comment]
> Oh, and playing around with this some more: We currently cannot set any of the boxplot.default arguments, can we? For example, range, varwidth, width, notch, etc. seem to be ignored at the moment.

It's a bit hidden, but `boxwex`, `staplewex`, and `outwex` at least are supported through `...`. In this case, adjusting  `boxwex` would have had a similar effect.

```r
tinyplot(Petal.Length ~ Species, data = iris2, boxwex = .75)
```

I didn't include support for `notch` because I personally don't like it (see also the warnings about weird behaviour in `?boxplot`) But `varwidth` and `range` are oversights; I'll add those. (I can add `notch` too if you would like to advocate for it.)

**Comment by zeileis** [comment]
I don't like `notch` either but I would still support it for compatibility with `boxplot`. And then maybe `outline` could be supported as well (even though I have never used it myself)?

**Comment by grantmcdermott** [comment]
Cool. I'll also add support for `boxwidth` as more direct argument alias that gets passed down to `boxplot(..., width = boxwidth)` internally (and so doesn't create a clash with our primary `tinyplot(..., width)` argument).
