### ISSUE TITLE
Wishlist: Refined methods for densities/histograms

### ISSUE THREAD

**Issue by zeileis** [grantmcdermott/tinyplot#21]
In addition to the `plot2.density` method from PR https://github.com/grantmcdermott/plot2/pull/18, it would be nice to have a formula-based interface:

    plot2(~ x | by, type = c("density", "histogram"), ...)

where it can be selected which display is used for `x` in each `by` group.

In addition to just lines it would be nice to support semi-transparent shaded areas below the lines as well (via `polygon()`). The area might also be opaque if we order the by groups (e.g., by median) from highest to lowest, which would yield a kind of ridge lines plot.

_GM edit: adding task items to track._

- [x] #61
- [x] #56
- [ ] #72

**Comment by grantmcdermott** [comment]
- [ ] formula interface for densities
- [ ] filled density shading

**Comment by harrelfe** [comment]
I would rather see `type='histogram'` or `'density`' handled in a general way where the user provides a function that transforms one variable into two dimensions (e.g., original value and height of estimated density function), and have the function also provide a few more details (e.g., type='l' vs. type='b' or 'p' or 'bar').

**Comment by grantmcdermott** [comment]
> I would rather see type='histogram' or 'density' handled in a general way where the user provides a function that transforms one variable into two dimensions (e.g., original value and height of estimated density function), and have the function also provide a few more details (e.g., type='l' vs. type='b' or 'p' or 'bar').

Thanks for the suggestion. I have something along those lines [here](https://github.com/grantmcdermott/plot2/issues/97) (see "User-supplied functions" near the bottom).
