### ISSUE TITLE
Documentation for multiple `by` variables

### ISSUE THREAD

**Issue by strengejacke** [grantmcdermott/tinyplot#213]
The documentation for `tinyplot`'s `by` argument says:

> grouping variable(s). ...

But it remains unclear how to define more than one variable. One could expect a list, e.g. `list(aq$Month, aq$grp)`, but that didn't work, instead, I had to use `interaction()`. It's clearer if the docs explicitly mention how to define more than 1 variable in `by`.

```r
tinyplot(
  y = aq$Temp,
  x = aq$Day,
  by = interaction(aq$Month, aq$grp),
  data = aq,
  pch = 16,
  cex = 2,
  frame = FALSE,
  grid = TRUE
)
```

**Comment by grantmcdermott** [comment]
Good point, thanks for raising.

I think we do a decent job somewhere in the docs explaining how this works for the formula method, but we could certainly explain better for the atomic method. FWIW, your approach of using `interaction` is what I would recommend in this case. I'll update the docs when I get chance...

**Comment by grantmcdermott** [comment]
Should be clearer now. Thanks for the suggestion!
