### ISSUE TITLE
Ribbon types without `ymin`/`ymax` should inherit from `y`

### ISSUE THREAD

**Issue by grantmcdermott** [grantmcdermott/tinyplot#224]
Otherwise you get nonsensical plots like:

``` r
tinyplot::plt(Petal.Length ~ Sepal.Length, data = iris, type = "ribbon")
```

![](https://i.imgur.com/nocz8py.png)

<sup>Created on 2024-10-07 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Another option would be to error out explicitly with warning that `ymin` and `ymax` are required args for `type = "ribbon"`. But I think inheriting from `y` (so that the above plot looks the same as a line plot) is a better default, since we already draw `y` as a line if it is provided.

(H/T @zeileis comment [here](https://github.com/grantmcdermott/tinyplot/pull/216#issuecomment-2396182586). I'll fix as part of the same PR.)

**Comment by zeileis** [comment]
I agree that resorting to a line plot is a good default.

Related question: Would we want to be able to specify `ymin` and `ymax` through the `formula`?

**Comment by grantmcdermott** [comment]
> Related question: Would we want to be able to specify ymin and ymax through the formula?

Yes!

Honestly, this is something that I'd love to have a "good" syntax for. I'm all ears if you have ideas. We should probably open a separate issue to discuss.

P.S. The way that base plot handles this AFAICT is to allow ymin/ymax passing through NSE. I can't think of an example off the top of my head, though...

**Comment by vincentarelbundock** [comment]
Not a strong preference, but I feel that we already have arguments called `ymin` and `ymax`, and it's generally good to have only one way of doing things, and to avoid overloading the formula. `by` is a very common use-case, and I think it might be confusing if the formula is used for more than that.

But again, this is a relatively weak preference.

**Comment by zeileis** [comment]
Well, we can either use standard non-standard evaluation when building the `model.frame()`. This would be like `weights = ...` or `offset = ...` in regression functions like `lm()` and `glm()`. So we could include `ymin` and `ymax` there. BTW: `weights` might also be handy, especially for categorical data but also for pre-binned data.

Alternatively, we could have formulas like `cbind(ymin, y, ymax) ~ x | by`. But then we would need to decide whether to turn multivariate responses into matrices or data frames etc.
