### ISSUE TITLE
Deprecate `ribbon.alpha`

### ISSUE THREAD

**Issue by vincentarelbundock** [grantmcdermott/tinyplot#225]
With https://github.com/grantmcdermott/tinyplot/pull/222 , I think `ribbon.alpha` should be moved to `type_ribbon()` and to other type-specific functions where they are relevant.

I think this is used in `by_bg` and I couldn't quite figure out how, so I didn't do this in the main PR.

**Comment by grantmcdermott** [comment]
Yeah, good shout. I'm happy to deprecate.

**Comment by grantmcdermott** [comment]
Closed by #244
