### ISSUE TITLE
Add `grid()` args to tpar?

### ISSUE THREAD

**Issue by grantmcdermott** [grantmcdermott/tinyplot#235]
At present, we support a simple logic argument for automatically drawing a grid all plots via `tpar(grid = TRUE)`.

But this doesn't give users much control over how their grids look, since it enforces the default colour ("lightgray"), line type ("dotted"), and width (`par("lwd")`).

It's not a huge deal, because users can adjust these settings for individual plots by passing `grid = grid(...)` in the `tinyplot` call.

```{r}
tinyplot(
    sin(0:100/10), axes = "l",
    grid = grid(col = "hotpink", lty = "solid")
)
```

But... thinking ahead to our goal of enabling themes (#234), maybe it's a low cost intervention to define these grid elements globally in `tpar(grid.col = 'lightgray", grid.lty = "dotted", grid. lwd = 1)`.

**Comment by zeileis** [comment]
I think it would be good to have control over this using standard evaluation so I'm in favor of adding `grid.col`, `grid.lty`, `grid.lwd` in `tpar()`. Maybe it would be useful to be able to pass them directly to `tinyplot()` as well?

**Comment by vincentarelbundock** [comment]
I'd vote yes for that(), which can have a ton of arguments, but I'd prefer limiting the number of arguments in tiny plot(), and the status quo already gives us an easy way to do this with grid=grid()
