### ISSUE TITLE
`type_function()`

### ISSUE THREAD

**Issue by vincentarelbundock** [grantmcdermott/tinyplot#248]
That would be nice, no?

Similar to: https://ggplot2.tidyverse.org/reference/geom_function.html

**Comment by grantmcdermott** [comment]
We had this as a desideratum in https://github.com/grantmcdermott/tinyplot/issues/97 (at the bottom of the OP). I marked as completed with your implementation of custom types support... but in retrospect those are different things.

Agree that this would be nice to support. Good call out.

**Comment by vincentarelbundock** [comment]
https://github.com/grantmcdermott/tinyplot/pull/250

**Comment by zeileis** [comment]
Should `"function"` also be added to the `types` in `sanitize_type`?

**Comment by vincentarelbundock** [comment]
Probably. Don't know if that would create problems, and might not have time to check for a while 😞

**Comment by zeileis** [comment]
Do you have any particular aspect that you think might be affected by this outside of `sanitize_type`?

I just quickly added `"function"` to the `types` and corresponding `switch()` in https://github.com/grantmcdermott/tinyplot/pull/267. It worked as intended in the examples I tried and the checks still worked ok as before. Should I simply push it into that PR?

**Comment by vincentarelbundock** [comment]
Yeah, I think it should fine. Just overlooked it.

**Comment by zeileis** [comment]
OK, added it in https://github.com/grantmcdermott/tinyplot/pull/267 now.
