### ISSUE TITLE
Duplicated axes

### ISSUE THREAD

**Issue by vincentarelbundock** [grantmcdermott/tinyplot#260]
If all facets on a row share the same vertical scale, we should probably only print the axis on the left facet.

Same thing vertically.

**Comment by grantmcdermott** [comment]
We enable this behavior manually if a user specifies `frame = FALSE` or
`axes = "l(t)"`.

I'm kind of reluctant to do this automatically as a default, but we could
easily enable it for specific themes (by setting either of the two
arguments above).
