### ISSUE TITLE
Move `xaxt` and `yaxt` to `tpar()`

### ISSUE THREAD

**Issue by vincentarelbundock** [grantmcdermott/tinyplot#261]
IIUC, the current arguments can lead to contradictions that are not obvious to resolve. For example,

```r
tinyplot(..., axes = "none", xaxt = "ticks", yaxt = "standard")
```

How about we set these rules instead?

1. `axes=FALSE`: Use "none" everywhere all the time since it is explicit.
2. `axes="none"`: Use "none" everywhere all the time since it is explicit.
3. `axes=TRUE`: Use `tpar("xaxt")` and `tpar("yaxt")`, with "standard" if undefined.

**Comment by zeileis** [comment]
I agree that the code line you give is not great but I think such contradictions are hard to avoid. Even with your proposal I would be able to do

```
tinyplot(..., axes = "standard", xaxt = "ticks", yaxt = "labels")
```

Hence, the rule I used was: First `axes` is set for both x-axis and y-axis. Subsequently, one or both of these can be overruled by `xaxt` and/or `yaxt`. So this is a bit like in CSS where the more special settings can overrule the more general settings.

Of course, I wouldn't recommend to set all three options simultaneously but I don't find it difficult to explain what happens.

**Comment by vincentarelbundock** [comment]
Yeah, that makes sense.

I wasn't familiar with that part of the code. It's interesting.

Closing.

**Comment by zeileis** [comment]
OK, good. If you want to improve the documentation in this regard, this would be much appreciated!
